version: '2'
services:
  springrestdata-app:
    image: springrestdata
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://springrestdata-postgresql:5432/springRestData
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  springrestdata-postgresql:
    extends:
      file: postgresql.yml
      service: springrestdata-postgresql
